version: "3"

services:
  backend:
    image: docker-nestjs-backend
    build: ./backend
    command: npm run start:dev
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    ports:
      - 3002:3000

  client:
    image: docker-gatsby-client
    build: ./client
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    ports:
      - "8000:8000"
      - "9929:9929"
      - "9230:9230"
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
    depends_on:
      - backend